print("xD nice try, but Serega is smorty dude :^)")
print("xD nice try, but Serega is smorty dude :^)")
print("xD nice try, but Serega is smorty dude :^)")
print("xD nice try, but Serega is smorty dude :^)")
print("xD nice try, but Serega is smorty dude :^)")
print("xD nice try, but Serega is smorty dude :^)")